-- Snowflake Setup for Data Warehouse Assistant
USE ROLE ACCOUNTADMIN;

-- Enable all Cortex LLM Models (including cross-region fallbacks) for the account
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY';

CREATE DATABASE IF NOT EXISTS ARCHITECTURE_STORE;
CREATE SCHEMA IF NOT EXISTS ARCHITECTURE_STORE.PUBLIC;

USE DATABASE ARCHITECTURE_STORE;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS ARCHITECTURE_STORE.PUBLIC.PROJECTS (
    ID           VARCHAR DEFAULT UUID_STRING() PRIMARY KEY,
    CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_NAME    VARCHAR,
    REQUIREMENTS VARIANT,
    DATA_PROFILE VARIANT,
    ARCHITECTURE VARIANT,
    SCHEMA_DESIGN VARIANT,
    PIPELINE     VARIANT,
    GOVERNANCE   VARIANT,
    DDL_SQL      TEXT,
    DOCUMENTATION TEXT,
    MERMAID_DIAGRAM TEXT,
    STATUS       VARCHAR DEFAULT 'draft',
    METADATA     VARIANT,
    HISTORY      VARIANT
);

-- Migration: Ensure diagram column is MERMAID_DIAGRAM
ALTER TABLE IF EXISTS ARCHITECTURE_STORE.PUBLIC.PROJECTS RENAME COLUMN GRAPHVIZ_DIAGRAM TO MERMAID_DIAGRAM;

CREATE TABLE IF NOT EXISTS ARCHITECTURE_STORE.PUBLIC.DEPLOY_LOG (
    ID              VARCHAR DEFAULT UUID_STRING() PRIMARY KEY,
    PROJECT_ID      VARCHAR,
    DEPLOYED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TARGET_DB       VARCHAR,
    TARGET_SCHEMA   VARCHAR,
    STATEMENTS_RUN  NUMBER,
    STATUS          VARCHAR,
    ERRORS          VARIANT
);

-- Grant permissions to the developer role
GRANT USAGE ON DATABASE ARCHITECTURE_STORE TO ROLE HEALTHCARE_POC_DEVELOPERS;
GRANT USAGE ON SCHEMA ARCHITECTURE_STORE.PUBLIC TO ROLE HEALTHCARE_POC_DEVELOPERS;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ARCHITECTURE_STORE.PUBLIC TO ROLE HEALTHCARE_POC_DEVELOPERS;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ARCHITECTURE_STORE.PUBLIC TO ROLE HEALTHCARE_POC_DEVELOPERS;

-- Grant Cortex AI capabilities to the developer role
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HEALTHCARE_POC_DEVELOPERS;
